# name|url|expected-title|min-entries|max-entries
light|https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt||10000|100000
normal|https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/multi-onlydomains.txt||50000|500000
pro|https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt||100000|500000
pro-plus|https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus-onlydomains.txt||100000|600000
ultimate|https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate-onlydomains.txt||100000|600000
