# name|url|expected-title|min-entries|max-entries
small|https://small.oisd.nl/domainswild2|oisd small|10000|200000
big|https://big.oisd.nl/domainswild2|oisd big|100000|2000000
nsfw|https://nsfw.oisd.nl/domainswild2|oisd nsfw|100000|1000000
nsfw-small|https://nsfw-small.oisd.nl/domainswild2|oisd nsfw_small|10000|100000
