# name|url|expected-title|min-entries|max-entries
small|https://dl.oisd.nl/oisd_small_surge.list|oisd small|10000|200000
big|https://dl.oisd.nl/oisd_big_surge.list|oisd big|100000|2000000
nsfw|https://dl.oisd.nl/oisd_nsfw_surge.list|oisd nsfw|100000|1000000
nsfw-small|https://dl.oisd.nl/oisd_nsfw_small_surge.list|oisd nsfw_small|10000|100000
